language: python

# use container-based travis-ci infrastructure
#sudo: false

# use legacy infrastructure
sudo: required

matrix:
  include:
    - python: "2.7"
      before_install:
        - pip install virtualenv

    - python: "3.4"
      addons:
        apt:
          packages:
          - python3-setuptools
          - python3-dev

install:
  - mkdir -p /tmp/logs/launchpy
  - python$TRAVIS_PYTHON_VERSION launch.py install

script:
  - python$TRAVIS_PYTHON_VERSION launch.py test

branches:
  only:
    - master
    - unstable