language: python

# use container-based travis-ci infrastructure
sudo: false

# use legacy infrastructure
#sudo: required

matrix:
  include:
    - python: "2.7"
      env: PYTHON_BINARY="python2.7"
      before_install:
        - pip install virtualenv

    - python: "3.4"
      env: PYTHON_BINARY="python3.4"
      addons:
        apt:
          packages:
          - python3-setuptools
          - python3-dev
      before_install:
# deactivate Travis-CI Python3 VirtualEnv, as it conflicts with the launch.py one
        - deactivate

    - python: "3.5"
      env: PYTHON_BINARY="python3.4"
      addons:
        apt:
          packages:
          - python3-setuptools
          - python3-dev
      before_install:
# deactivate Travis-CI Python3 VirtualEnv, as it conflicts with the launch.py one
        - deactivate

install:
  - mkdir -p /tmp/logs/launchpy
  - ${PYTHON_BINARY} launch.py install

script:
  - ${PYTHON_BINARY} launch.py test

branches:
  only:
    - master
    - unstable